language: objective-c

branches:
     only:
          - master

     xcode_project: SonosBar.xcodeproj
     xcode_scheme: SonosBarTests
     osx_image: xcode7
     xcode_sdk: macosx10.10 

     script:
         - xcodebuild clean build test -project SonosBar.xcodeproj -scheme SonosBarTests
